services:
  postgresql:
    container_name: postgresql
    build:  ./postgresql
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/15/main
    networks:
      - network

  app:
    container_name: app
    build: ./app
    depends_on:
      - postgresql
    env_file: .env
    networks:
      - network
    ports:
      - "8000:8000"

networks:
  network:
    name: ${NETWORK_NAME}
    driver: bridge

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data