# Generated by Django 5.0.1 on 2024-01-22 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='initialized')),
                ('target_value', models.FloatField(default=100.0)),
                ('target_value_delta_sign', models.SmallIntegerField(default=1)),
                ('player_value', models.FloatField(default=50)),
                ('current_score', models.FloatField(default=0)),
                ('target_score', models.FloatField(default=1000)),
                ('player_move_up', models.BooleanField(default=False)),
                ('player_move_down', models.BooleanField(default=False)),
                ('player_move_speed', models.FloatField(default=1)),
                ('init_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(null=True)),
                ('last_update_time', models.DateTimeField(null=True)),
                ('last_user_request_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
