# Generated by Django 5.0.1 on 2024-01-22 16:09

import django.db.models.deletion
import django.utils.timezone
import transcendence.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150, unique=True)),
                ('picture', models.ImageField(default='default_pp.png', upload_to=transcendence.models.get_picture_path)),
                ('rating', models.FloatField(default=1500)),
                ('last_request_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
